future: true
permalink: /:title/
url: http://chenyime.github.io
name: chenyime
author: chenyimei
qq: 790299972
email: sysuyimei@gmail.com

duoshuo: chenyimei
beian: 
cnzz: 
weibo: 
github: chenyime
about: "这里是 陈亿枚 的个人博客，创建于 2018 年。"

safe: true
paginate: 20
