future: true
permalink: /:title/
url: http://chenyime.github.io
name: 陈亿枚
author: 陈亿枚
qq: 790299972
email: sysuyimei@gmail.com

duoshuo: yourname
beian: 
cnzz: 
weibo: 
github: yourID
about: "这里是 chenyimei 的个人博客，创建于 2018 年。"

safe: true
paginate: 20
